truncate table itcast_dwd.dwd_customer_clue;
truncate table itcast_dwd.dwd_customer_relationship;
insert into table itcast_dwd.dwd_customer_relationship partition (yearinfo, monthinfo, dayinfo)
select
id,
create_date_time,
deleted,
customer_id,
origin_type,
if(itcast_school_id is null or itcast_school_id = 0,'-1',itcast_school_id)as itcast_school_id,
if(itcast_subject_id is null or itcast_subject_id = 0,'-1',itcast_subject_id)    as itcast_subject_id,
creator,
if(origin_type in ('NETSERVICE', 'PRESIGNUP'), 1, 0)as origin_type_stat,
hour(create_date_time)hourinfo,
year(create_date_time)yearinfo,
month(create_date_time)monthinfo,
day(create_date_time)dayinfo
from itcast_ods.customer_relationship
where deleted='false';







set hive.exec.dynamic.partition.mode=nonstrict;
insert into table itcast_dwd.dwd_customer_clue partition(yearinfo, monthinfo, dayinfo)
select id,
       unix_timestamp(create_date_time) as create_date_time,
       unix_timestamp(update_date_time) as update_date_time,
       deleted,
       customer_id,
       customer_relationship_id,
       session_id,
       sid,
       cc.status,
       cc.`user`,
       create_time,
       platform,
       s_name,
       seo_source,
       seo_keywords,
       ip,
       referrer,
       from_url,
       landing_page_url,
       url_title,
       to_peer,
       manual_time,
       begin_time,
       reply_msg_count,
       total_msg_count,
       nvl(msg_count, 0)    as msg_count,
       cc.comment,
       finish_reason,
       finish_user,
       end_time,
       platform_description,
       browser_name,
       os_info,
       area,
       country,
       province,
       city,
       creator,
       name,
       idcard,
       phone,
       itcast_school_id,
       itcast_school,
       itcast_subject_id,
       itcast_subject,
       wechat,
       qq,
       email,
       gender,
       cc.level,
       origin_type,
       if(origin_type in ('NETSERVICE', 'PRESIGNUP'), 1, 0)                 as origin_type_stat,
       information_way,
       working_years,
       technical_directions,
       customer_state,
       valid,
       anticipat_signup_date,
       clue_state,
       if(clue_state in ('VALID_NEW_CLUES', 'VALID_PUBLIC_NEW_CLUE'), 1, 0) as clue_state_stat,
       scrm_department_id,
       superior_url,
       superior_source,
       landing_url,
       landing_source,
       info_url,
       info_source,
       origin_channel,
       course_id,
       course_name,
       zhuge_session_id,
       is_repeat,
       tenant,
       activity_id,
       activity_name,
       follow_type,
       shunt_mode_id,
       shunt_employee_group_id,
       substr(create_date_time, 12, 2)                                      as hourinfo,
       substr(create_date_time, 1, 4)                                       as yearinfo,
--        quarter(create_date_time)                                            as quarterinfo,
       substr(create_date_time, 6, 2)                                       as monthinfo,
       substr(create_date_time, 9, 2)                                       as dayinfo
from itcast_ods.customer_clue cc
where deleted = 'false'
and cc.id<1500;